import type { CategoryId } from "@/content/types";

/**
 * Where each Lottie scene plays.
 *
 * Every scene lives in public/lottie and is generated by
 * scripts/lottie/build.mjs. /de/hero-varianten renders them all side by side.
 */
export const HERO_ANIMATIONS = [
  {
    name: "hero-prosumer",
    title: { de: "Prosumer", en: "Prosumer" },
    note: {
      de: "Sonne, Wind, PV-Dach, Speicher: die ganze Geschichte des Wikis in einem Bild.",
      en: "Sun, wind, a PV roof, a battery: the whole story of this wiki in one picture.",
    },
    usedFor: { de: "Startseite", en: "Home page" },
  },
  {
    name: "hero-netzpuls",
    title: { de: "Netzpuls", en: "Grid pulse" },
    note: {
      de: "Energie läuft von der Erzeugung über zwei Umspannpunkte zu drei Abnahmestellen. Die Endknoten tragen ein Symbol statt nur ein Kreis zu sein.",
      en: "Energy runs from generation through two transformer points to three offtake points. The end nodes carry a symbol rather than being plain circles.",
    },
    usedFor: { de: "Thema „Markt & Grundlagen“", en: "Topic “Market & fundamentals”" },
  },
  {
    name: "hero-tarifkurve",
    title: { de: "Tarifkurve", en: "Tariff curve" },
    note: {
      de: "Ein Börsentag als Balkenfeld. Ein durchgehender Verlauf codiert die Höhe, ein Playhead wandert über den Tag.",
      en: "A day on the exchange as a field of bars. A continuous gradient encodes the level, a playhead travels across the day.",
    },
    usedFor: { de: "Thema „Tarife & Preisbildung“", en: "Topic “Tariffs & pricing”" },
  },
  {
    name: "hero-zaehler",
    title: { de: "Zähler", en: "Meter" },
    note: {
      de: "Ein Instrument, das erwacht: Zeiger und Gradientenbogen laufen synchron, Skalenstriche wandern mit, Ringe strahlen nach außen ab.",
      en: "An instrument waking up: the needle and the gradient arc move in sync, the scale ticks travel with them, rings radiate outwards.",
    },
    usedFor: { de: "Thema „Zähler & Messwesen“", en: "Topic “Meters & metering”" },
  },
  {
    name: "energy-flow",
    title: { de: "Leitung", en: "Power line" },
    note: {
      de: "Die ruhige erste Fassung: Mast, Zähler, Haus, ein Puls auf der Leitung.",
      en: "The calm first draft: a pylon, a meter, a house, one pulse travelling down the line.",
    },
    usedFor: { de: "Thema „Sparten“", en: "Topic “Commodities”" },
  },
  {
    name: "hero-anlagen",
    title: { de: "Energiehub", en: "Energy hub" },
    note: {
      de: "Alles hinter dem Zähler hängt an einem Hub: PV speist ein, Wärmepumpe, Speicher und Wallbox beziehen. Jedes Gerät tut das eine, was es tut – der Lüfter dreht, der Speicher lädt, die Wallbox blinkt.",
      en: "Everything behind the meter hangs off one hub: PV feeds in, heat pump, battery and wallbox draw. Each device does the one thing it does – the fan spins, the battery charges, the wallbox blinks.",
    },
    usedFor: { de: "Thema „Anlagen & Technik“", en: "Topic “Systems & equipment”" },
  },
  {
    name: "hero-abrechnung",
    title: { de: "Abschlag & Abrechnung", en: "Instalments & statement" },
    note: {
      de: "Elf gleiche Abschläge wachsen Monat für Monat, die gestrichelte Linie zeichnet das Abschlagsniveau mit. Im zwölften Feld setzt die Jahresabrechnung die Differenz.",
      en: "Eleven equal instalments rise month by month, the dashed line traces the instalment level. In the twelfth slot the annual statement settles the difference.",
    },
    usedFor: { de: "Thema „Abrechnung & Zahlung“", en: "Topic “Billing & payment”" },
  },
  {
    name: "hero-kunde",
    title: { de: "Lieferantenwechsel", en: "Supplier switch" },
    note: {
      de: "Ein Haushalt, drei Lieferanten. Der aktive Vertrag wandert alle Sekunde weiter – Wechseln ist ein normaler Vorgang, keine Ausnahme.",
      en: "One household, three suppliers. The active contract moves on every second – switching is routine, not the exception.",
    },
    usedFor: { de: "Thema „Kunde, Portal & Prozesse“", en: "Topic “Customer, portal & processes”" },
  },
  {
    name: "hero-recht",
    title: { de: "Waage", en: "Balance" },
    note: {
      de: "Energie auf der einen Schale, Steuern und Umlagen stapeln sich auf der anderen. Der Balken neigt sich, hält, kehrt zurück.",
      en: "Energy on one pan, taxes and levies stacking onto the other. The beam tilts, holds, returns.",
    },
    usedFor: { de: "Thema „Recht, Steuern & Umlagen“", en: "Topic “Law, taxes & levies”" },
  },
] as const;

export type HeroAnimationName = (typeof HERO_ANIMATIONS)[number]["name"];

/** The scene on the home page hero. */
export const HERO_ANIMATION: HeroAnimationName = "hero-prosumer";

/** Banner animation per topic, each built for the subject of its section. */
export const CATEGORY_ANIMATIONS: Record<CategoryId, HeroAnimationName> = {
  grundlagen: "hero-netzpuls",
  sparten: "energy-flow",
  anlagen: "hero-anlagen",
  tarife: "hero-tarifkurve",
  messwesen: "hero-zaehler",
  abrechnung: "hero-abrechnung",
  kunde: "hero-kunde",
  recht: "hero-recht",
};
