import type { CategoryId } from "@/content/types";

/**
 * Where each Lottie scene plays.
 *
 * Every scene lives in public/lottie and is generated by
 * scripts/lottie/build.mjs. /de/hero-varianten renders them all side by side.
 */
export const HERO_ANIMATIONS = [
  {
    name: "hero-prosumer",
    title: "Prosumer",
    note: "Sonne, Wind, PV-Dach, Speicher: die ganze Geschichte des Wikis in einem Bild.",
    usedFor: "Startseite",
  },
  {
    name: "hero-netzpuls",
    title: "Netzpuls",
    note: "Energie läuft von der Erzeugung über zwei Umspannpunkte zu drei Abnahmestellen. Die Endknoten tragen ein Symbol statt nur ein Kreis zu sein.",
    usedFor: "Thema „Markt & Grundlagen“",
  },
  {
    name: "hero-tarifkurve",
    title: "Tarifkurve",
    note: "Ein Börsentag als Balkenfeld. Ein durchgehender Verlauf codiert die Höhe, ein Playhead wandert über den Tag.",
    usedFor: "Thema „Tarife & Preisbildung“",
  },
  {
    name: "hero-zaehler",
    title: "Zähler",
    note: "Ein Instrument, das erwacht: Zeiger und Gradientenbogen laufen synchron, Skalenstriche wandern mit, Ringe strahlen nach außen ab.",
    usedFor: "Thema „Zähler & Messwesen“",
  },
  {
    name: "energy-flow",
    title: "Leitung",
    note: "Die ruhige erste Fassung: Mast, Zähler, Haus, ein Puls auf der Leitung.",
    usedFor: "Thema „Sparten“",
  },
] as const;

export type HeroAnimationName = (typeof HERO_ANIMATIONS)[number]["name"];

/** The scene on the home page hero. */
export const HERO_ANIMATION: HeroAnimationName = "hero-prosumer";

/**
 * Optional banner animation per topic. Categories without an entry simply get
 * a text-only header — better an honest gap than a scene that does not fit the
 * subject.
 */
export const CATEGORY_ANIMATIONS: Partial<Record<CategoryId, HeroAnimationName>> =
  {
    grundlagen: "hero-netzpuls",
    sparten: "energy-flow",
    tarife: "hero-tarifkurve",
    messwesen: "hero-zaehler",
  };
